spring:
  application:
    name: checkout-service
  datasource:
    url: jdbc:postgresql://localhost:5433/checkout_service_db_test
    username: bookshop_user
    password: bookshop_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
