services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # Produktionsdatenbank
  book-service-prod:
    image: postgres:latest
    container_name: book-service-prod
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: book_service_db_prod
    ports:
      - "5432:5432" # Port für PROD
    volumes:
      - book_service_prod_data:/var/lib/postgresql/data

  # Testdatenbank
  book-service-test:
    image: postgres:latest
    container_name: book-service-test
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: book_service_db_test
    ports:
      - "5433:5432" # Port für TEST und LOCAL
    volumes:
      - book_service_test_data:/var/lib/postgresql/data

  order-service-test:
    image: postgres:latest
    container_name: order-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: order_service_db
    ports:
      - "5434:5432"
    volumes:
      - order_service_data:/var/lib/postgresql/data

  shopping-cart-service-test:
    image: postgres:latest
    container_name: shopping-cart-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: shopping_cart_service_db
    ports:
      - "5435:5432"
    volumes:
      - shopping_cart_service_data:/var/lib/postgresql/data

  user-service-test:
    image: postgres:latest
    container_name: user-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: user_service_db
    ports:
      - "5436:5432"
    volumes:
      - user_service_data:/var/lib/postgresql/data

  notification-service-test:
    image: postgres:latest
    container_name: notification-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: notification_service_db
    ports:
      - "5437:5432"
    volumes:
      - notification_service_data:/var/lib/postgresql/data

  checkout-service-test:
    image: postgres:latest
    container_name: checkout-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: checkout_service_db
    ports:
      - "5438:5432"
    volumes:
      - checkout_service_data:/var/lib/postgresql/data

volumes:
  book_service_prod_data:
  book_service_test_data:
  order_service_data:
  shopping_cart_service_data:
  checkout_service_data:
  user_service_data:
  notification_service_data:
