services:
  # Produktionsdatenbank
  book-service-prod:
    image: postgres:latest
    container_name: book-service-prod
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: book_service_db_prod
    ports:
      - "5432:5432" # Port für PROD
    volumes:
      - book_service_prod_data:/var/lib/postgresql/data

  # Testdatenbank
  book-service-test:
    image: postgres:latest
    container_name: book-service-test
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: book_service_db_test
    ports:
      - "5433:5432" # Port für TEST und LOCAL
    volumes:
      - book_service_test_data:/var/lib/postgresql/data

  order-service-test:
    image: postgres:latest
    container_name: order-postgres
    environment:
      POSTGRES_USER: bookshop_user
      POSTGRES_PASSWORD: bookshop_password
      POSTGRES_DB: order_service_db
    ports:
      - "5434:5432"
    volumes:
      - order_service_data:/var/lib/postgresql/data

volumes:
  book_service_prod_data:
  book_service_test_data:
  order_service_data:
